replicaCount: 1

image:
  repository: ghcr.io/nrf24l01/k8s-pobeda-backend
  tag: latest
  pullPolicy: IfNotPresent

frontend:
  replicaCount: 1
  image:
    repository: ghcr.io/nrf24l01/k8s-pobeda-frontend
    tag: latest
    pullPolicy: IfNotPresent
  resources: {}

gateway:
  replicaCount: 1
  image:
    repository: nginx
    tag: 1.28-alpine
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  resources: {}

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

rbac:
  create: true

service:
  type: ClusterIP
  port: 8080

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

env:
  httpAddr: ":8080"
  corsAllowOrigin: "*"

resources: {}

livenessProbe:
  path: /healthz
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  path: /healthz
  initialDelaySeconds: 5
  periodSeconds: 10
