apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-pobeda-backend.fullname" . }}-frontend
  labels:
    {{- include "k8s-pobeda-backend.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "k8s-pobeda-backend.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
