apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-pobeda-backend.fullname" . }}-gateway
  labels:
    {{- include "k8s-pobeda-backend.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
data:
  default.conf: |
    server {
      listen 80;
      server_name _;

      # Nginx ping
      location = /ng/ping {
        access_log off;
        add_header Content-Type text/plain;
        return 200 "Nginx status OK\n";
      }

      location /api/ {
        proxy_pass http://{{ include "k8s-pobeda-backend.fullname" . }}:{{ .Values.service.port }}/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_pass_header Access-Control-Allow-Origin;
        proxy_pass_header Access-Control-Allow-Methods;
        proxy_pass_header Access-Control-Allow-Headers;
        proxy_pass_header Access-Control-Allow-Credentials;
      }

      location /healthz {
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://{{ include "k8s-pobeda-backend.fullname" . }}:{{ .Values.service.port }}/healthz;
      }

      location / {
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://{{ include "k8s-pobeda-backend.fullname" . }}-frontend:3000;
      }
    }
